version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: netbox
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: netbox
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    restart: unless-stopped
  netbox:
    image: netboxcommunity/netbox:latest
    depends_on:
      - postgres
      - redis
    environment:
      - ALLOWED_HOSTS=*
    ports:
      - "8080:8080"
    volumes:
      - ./data/netbox:/opt/netbox/netbox/media
    restart: unless-stopped